### ISSUE TITLE
Limit the number of files per directory

### ISSUE THREAD

**Issue by bboure** [atom/tree-view#1082]
Some directories like those containing database migrations can usually grow really quickly (currently, mine has > 1200 files).
Most of these files are usually not even used on a daily basis but when you need to open that directory, it makes the tree-view slow to unfold and it creates that long and annoying scrollbar.
Usually, you just need the latest created files as you are working on them or checking something that was done recently...
In this kind of situation, it would be great to be able to add a filter to limit a directory to n files (i.e: the n last created files, or files created since a given date) and leave the other ones hidden.

**Comment by rsese** [comment]
Hey @bboure :wave:  We require the issue template to be filled out for new issues but additionally, I think this is close enough to https://github.com/atom/atom/issues/1847 that we'll also close as a duplicate.

---

Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests, even for feature requests (you can just point out where something in the template doesn't apply). We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
