### ISSUE TITLE
Red underscore line under file name in tree-view

### ISSUE THREAD

**Issue by ikzjfr0** [atom/tree-view#1085]
Atom 1.16.0 under MacOS

I recently got a problem like attached, which makes me unable to click any files under tree-view.
Anyone has met similar issues? 

![image](https://cloud.githubusercontent.com/assets/6456056/25550101/c3ee0a10-2cb9-11e7-8a99-df1ee343bdd9.png)

**Comment by 50Wliu** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
