### ISSUE TITLE
Tree View pane on the right hand side

### ISSUE THREAD

**Issue by ruslankonev** [atom/tree-view#1102]
Hello, on the Atom Beta 1.18 I am not found the settings "Toggle Side". Is this issue only in Beta release?

**Comment by bradybus** [comment]
@ruslankonev 
I am on the Atom 1.17 release, (I believe it is now the stable release?). After the update from Atom 1.16, my selection in the tree-view settings panel to "Show On Right Side" no longer works. Tree-view is permanently in the dock on the left hand side of the screen. So it doesn't seem like just a Beta issue. Maybe just something being removed altogether? Hope not, I personally prefer the right side.

Anyone know how to move a dock? I saw in the release notes the package creator has to have a 'default location' set for the dock location (if a dock is used). Wonder if there is a way for the user (us) to change that to a non-default location?

Thanks for the help!

**Comment by 50Wliu** [comment]
Please see the FAQ: https://discuss.atom.io/t/where-did-the-show-tree-view-on-right-side-option-go/42762/1

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* [The Atom Flight Manual](http://flight-manual.atom.io)
* [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.
