### ISSUE TITLE
`Show On Right Side` option does not work in Atom v0.17.0

### ISSUE THREAD

**Issue by andreapavoni** [atom/tree-view#1104]
### Prerequisites

* [X] Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
* [X] Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
* [X] Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
* [X] Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom

### Description
Since Atom v0.17.0 the tree-view does not show on the right, even if `Show On Right Side` option in tree-view settings is checked.

### Steps to Reproduce

1. Upgrade Atom to v0.17.0
2. Set `Show On Right Side` option in tree-view settings
2. Open/Toggle tree-view

**Expected behavior:** Tree view should be shown on the right side of the editor.

**Actual behavior:** It still remains on the left side

**Reproduces how often:** Always

### Versions

```
> atom --version
Atom    : 1.17.0
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0
```
```
> apm --version
apm  1.17.0
npm  3.10.5
node 6.9.5 x64
python 2.7.13
git 2.13.0
```

**Comment by 50Wliu** [comment]
Please see the FAQ: https://discuss.atom.io/t/where-did-the-show-tree-view-on-right-side-option-go/42762/1

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* [The Atom Flight Manual](http://flight-manual.atom.io)
* [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.
