### ISSUE TITLE
Escape no longer returns focus to editor

### ISSUE THREAD

**Issue by spalger** [atom/tree-view#1113]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

As of atom 1.18.0-beta0, focussing a file with the `tree-view:reveal-active-file` command then pressing the escape key no longer restores focus to the editor.

### Steps to Reproduce

1. Open a file
1. Focus the editor
2. Execute `tree-view:reveal-active-file` command
3. Press escape key

**Expected behavior:** Focus should be restored to the editor

**Actual behavior:** Focus is held by the tree-view

**Reproduces how often:** 100% of the time

### Versions

macOS 10.12.5
atom 1.18.0-beta0
tree-view 0.217.0-7

**Comment by rsese** [comment]
Thanks for the report!  I had 1.16.0 installed on another machine and can confirm that focus did return to the open file following your steps to reproduce but the actual behavior is as you described in 1.18.0-beta0 and in 1.17.0.

**Comment by llondon6** [comment]
I'm also experiencing this issue. A fix would be much appreciated.

**Comment by Brock-Wood** [comment]
I thought I was experiencing this issue, but It turned out to be 'synced-sidebar' package.
https://github.com/peterdotjs/atom-synced-sidebar/issues/33

**Comment by jasonrudolph** [comment]
As far as I can tell, this is a side effect of Atom 1.17 moving the tree view from a [`Panel`](https://atom.io/docs/api/v1.17.2/Panel) to a [`Dock`](https://atom.io/docs/api/v1.17.2/Dock).

In Atom 1.16, with the tree-view focused, hitting `escape` triggers [this keybinding defined in atom/atom](https://github.com/atom/atom/blob/1a60c450caac364203510fbbaf4cd07b3df41088/keymaps/base.cson#L21-L22):

```cson
'.tool-panel.panel-left, .tool-panel.panel-right':
  'escape': 'tool-panel:unfocus'
```

In Atom 1.17, with the tree-view focused, hitting `escape` triggers no keybindings at all.

Because the keybinding above applied to anything that existed in the left or right tool panels, you could argue that we should define a similar keybinding for docks. However, I think it might be too soon to say whether we want `escape` to universally provide this behavior for all docks. I'd prefer to give package authors time to make use of docks for a while before implementing any global keybindings for docks.

For now, I'm leaning toward adding an `escape` keybinding to tree-view. With the tree view focused, hitting `escape` would focus the active item in the workspace center.

What do y'all think?

**Comment by pixilz** [comment]
@jasonrudolph I can't see any problems with your proposed solution.
