### ISSUE TITLE
Disable collapse indicator on hover

### ISSUE THREAD

**Issue by mobitar** [atom/tree-view#1125]
The newest version of the Atom treeview seems to show this little thing when I hover over the treeview:

<img width="488" alt="screen shot 2017-06-07 at 8 39 36 am" src="https://user-images.githubusercontent.com/3277844/26881376-db698f4a-4b5c-11e7-8e6b-7628cb271615.png">

With all due respect, it is _extremely_ annoying, and I don't need to be reminded it's collapsable every time I hover over the treeview. I'm also well aware of the cmd+\ shortcut that hides it anyway.

Is there anyway to disable this?

**Comment by 50Wliu** [comment]
You can disable it by either:
* Using the "Hide dock toggle buttons" option in the One Dark and One Light UI themes
* Adding the CSS in https://discuss.atom.io/t/hide-the-new-tree-view-dock-toggle-button/42793/2?u=wliu to your `styles.less`

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* [The Atom Flight Manual](http://flight-manual.atom.io)
* [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.
