### ISSUE TITLE
My tree-view shows text 'Project' on top which doesn't exist before. How can I hide this text

### ISSUE THREAD

**Issue by turgunovm** [atom/tree-view#1126]
![photo_2017 06 08_05 34 56 jpg 1280x719](https://user-images.githubusercontent.com/9491986/26907332-60bcf77c-4c0c-11e7-8228-3f9b0bcf1135.png)

**Comment by 50Wliu** [comment]
Thanks for reaching out!

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* [The Atom Flight Manual](http://flight-manual.atom.io)
* [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.

**Comment by 50Wliu** [comment]
Though, try this in your `styles.less`:
```less
atom-dock .tab-bar[is="atom-tabs"]
{
    display: none;
}
```
