### ISSUE TITLE
Feature request: Show Add Project Folder button when tree view is empty

### ISSUE THREAD

**Issue by miguelcg** [atom/tree-view#1157]
### Description

As a user I would like to see a button to add a project folder in the tree view just when this is empty.

### Steps to Reproduce

1. Open Atom
2. Show Tree View
3. Remove all project folders (if any)

**Expected behavior:** I can see a button to add a project folder in the tree view

**Actual behavior:** There is nothing in the tree view

Happy to open a PR if this is something in the roadmap.

**Comment by lee-dohm** [comment]
Thanks for the suggestion.

We agree that this could be useful in some cases. It isn't something that we are going to work on independently, but I'm going to refer to https://github.com/atom/atom/issues/10517 so that when we make time for that redesign, this will be considered as part of that effort.

Thanks again :+1:
