### ISSUE TITLE
Tooltip 'Working Sets...' hangs

### ISSUE THREAD

**Issue by tibistibi** [atom/tree-view#1215]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

The tooltip 'Working Sets...' hangs. It stay's here for ever and will not close. Like this:
![image](https://user-images.githubusercontent.com/1875634/34033804-170cf6bc-e17c-11e7-9276-69d46558144b.png)

### Steps to Reproduce
Open Atom and there it is.

**Expected behavior:** 
The tooltip to close

**Actual behavior:**
It hangs

**Reproduces how often:**
100%

### Versions
Atom    : 1.22.1
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0
apm  1.18.8
npm  3.10.10
node 6.9.5 x64
python 2.7.12
git 2.7.4
Ubuntu 16.04

i have cleared my atom cache (but did not change any thing)

**Comment by rsese** [comment]
Thanks for the report!  This looks like functionality from https://github.com/facebook/nuclide:

https://nuclide.io/docs/features/working-sets/

It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down. You should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).
