### ISSUE TITLE
Option to disable lowered opacity on Tree View gitignored files/folders

### ISSUE THREAD

**Issue by InternetJohnny** [atom/tree-view#1299]
## Problem

Currently there are two options if you use .gitignore:
- You can set '**Exclude VCS ignored files**' to **True** and hide the files from Tree View
- You can set it to **False** and show them in the Tree View.

The problem with the second option is that it changes the opacity of the files and folders, making them much harder to see.
For example, Sass projects will typically gitignore .scss files and keep .css ones, but you would want Atom to show .scss files because they will be worked on.

## Solution

Adding an extra option next to '**Exclude VCS ignored files**'. For example:

- [ ] Exclude VCS ignored files
- [ ] Mark ignored files with lowered opacity

## Current Workaround

My current workaround is to add:

`.status-ignored {`
`color: rgba(157, 165, 180, 1)!important;`
`}`

to "styles.less"
This is a poor solution because it is theme specific, and most users will not bother finding this setting, instead conforming to removing .scss from their .gitignore

**Comment by rsese** [comment]
Thanks for the suggestion!

> This is a poor solution because it is theme specific, and most users will not bother finding this setting, instead conforming to removing .scss from their .gitignore

Though it's maybe not an ideal solution, if this can be addressed with a style change, we prefer that folks take advantage of Atom's customizability, especially since we're unlikely to work on feature requests at the moment as mentioned in the issue template.  Since adding a setting for this isn't something the team would prioritize, we'll close for now but thanks again for your suggestion.
