### ISSUE TITLE
treeview not working

### ISSUE THREAD

**Issue by mattcmiller** [atom/tree-view#1312]
Tree view is not working for me anymore. Just stopped opening automatically and when I open a project its not showing any files or folders in the side bar.

**Comment by rsese** [comment]
Thanks for the report! Can you fill out the issue template information? The format and information in the template is super helpful for us when triaging issues (for example, what version of Atom you're running and what operating system).  Also, how exactly are you opening a project?  From the command line or from your operating system's file manager?

In 1.36, opening a single file will now open without populating the tree view:

https://blog.atom.io/2019/04/09/atom-1-36.html#id=%22open-a-single-file-without-its-parent-directory%22

But that's only when opening a single file and you mentioned that you were opening a project.

---

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
