### ISSUE TITLE
`treeView.entryForPath` returns null

### ISSUE THREAD

**Issue by ashthespy** [atom/tree-view#1319]
### Description

Cross posting from [`git-plus/issues/786`](https://github.com/akonwi/git-plus/issues/786#issuecomment-507598784)

`treeView.entryForPath()` seems to return null for a path to a currently open project during initial start up, leading to fixes such as https://github.com/akonwi/git-plus/commit/e2704c0c656dc6e9ab3532591372440ea01ac993 

Any ideas what could cause this?

### Versions
Atom `v1.38.2`
```
ares: "1.10.1-DEV"
chrome: "61.0.3163.100"
electron: "2.0.18"
http_parser: "2.7.0"
modules: "57"
nghttp2: "1.25.0"
node: "8.9.3"
openssl: "1.0.2n"
uv: "1.15.0"
v8: "6.1.534.41"
zlib: "1.2.11"
```

**Comment by rsese** [comment]
Thanks for the report!  Can you fill out the rest of the issue template?  In particular, we would need steps to reproduce and some background on why this is an issue for Atom rather than https://github.com/akonwi/git-plus (e.g. are there other examples of this happening outside of https://github.com/akonwi/git-plus?).
