### ISSUE TITLE
Show in file manager opens vs code instead of filemanager

### ISSUE THREAD

**Issue by SpikePy** [atom/tree-view#1326]
### Description

If is want to show a file i the manager it opens **vs code** instead of filemanager

### Steps to Reproduce

1. Right click on file/folder
2. select "show in file manager"

**Expected behavior:**

open nautilus or other file manager that is installed

**Actual behavior:**

opens file in vs code

**Reproduces how often:**

always

### Versions

1.39.1 on arch linux

### Additional Information

You should also be able to configure which file manager to use. because lots of users have installed multiple (for me its nautilus and thunar)

**Comment by Aerijo** [comment]
This is [handled by Electron](https://github.com/electron/electron/blob/e1824c00a9cc77f74265bb520c40e360f69e7cb0/shell/common/platform_util_linux.cc#L61-L67), which uses the default viewer as seen by `xdg-open`. You have set VS Code as your preferred viewer at some point, intentionally or otherwise.

**Comment by SpikePy** [comment]
Thank you, found the problem and fixed it with: `xdg-mime default org.gnome.Nautilus.desktop inode/directory`.
