### ISSUE TITLE
Add an option for case-sensitive sort order

### ISSUE THREAD

**Issue by zhanzhenzhen** [atom/tree-view#235]
The sort order is now case-insensitive. But that brings the inconsistency with the GitHub web pages. Could you make it case-sensitive, or add an option for that?

**Comment by hnordt** [comment]
Looks like Atom doesn't like case-sentitive sorting. Atom `sort-lines` package doesn't support case-sensitive sorting too.

**Comment by TrevorBurnham** [comment]
I've created a PR for this: https://github.com/atom/tree-view/issues/916

**Comment by lee-dohm** [comment]
Thank you everyone for your feedback and interest.

We've decided that we aren't going to add this feature and that we aren't going to accept PRs for more customized sort orders in the Tree View.

**Comment by cristian-sima** [comment]
Why not? It is usefull for the case of a Redux/React project, organized with a lot of modules like here https://www.smashingmagazine.com/2016/09/how-to-scale-react-applications/

![image](https://user-images.githubusercontent.com/12199042/36597879-29991f4a-18b3-11e8-9cc9-404d505ea40f.png)

**Comment by lee-dohm** [comment]
1. Because sort orders are one of those fiddly things where everyone wants their own super-custom preferences met
1. Offering more than one means that we:
    1. Have to design a set of options for them
    1. Have to come up with descriptive, easy-to-understand language for what are often very subjective preferences
    1. Have to spend a lot of time diagnosing whether people's issues are real bugs or just another sort order that they want

Or ... we can punt on the whole thing and rely on the fact that the tree-view is open source and if people really want a different sort order, they can fork the tree-view to add and support it themselves.

We've opted for the latter.
