### ISSUE TITLE
the reveal command does not scroll the tree view when needed

### ISSUE THREAD

**Issue by cognominal** [atom/tree-view#271]
that is, when the revealed file is out of view. It should scroll the tree view to make the file visible

**Comment by izuzak** [comment]
@cognominal I'm having trouble reproducing this:

![tree](https://cloud.githubusercontent.com/assets/38924/5988851/6de7b7be-a972-11e4-8490-425b9e2e1e2a.gif)

Can you still reproduce the problem?

**Comment by cognominal** [comment]
Yes, I can reproduce the problem. But I realize it happens only when in certain cases.
Below, a case where it works and a case where it does not.

![reveal](https://cloud.githubusercontent.com/assets/16176/5991786/95d5bee4-aa06-11e4-8b96-859e5d8fa379.gif)

**Comment by gradlehubtest** [comment]
Experiencing this problem consistently +1

**Comment by aknuds1** [comment]
Experiencing this problem consistently +1

**Comment by izuzak** [comment]
Yeah, I can reproduce now as well, but not sure in which cases _exactly_ it happens. It's relatively easy to reproduce it with nested files in the atom/atom repository:

![treeview](https://cloud.githubusercontent.com/assets/38924/6268042/b9667eb0-b849-11e4-9614-8e1ab22f3b3e.gif)


Thanks @cognominal and @aknuds1 :cake:

**Comment by viddo** [comment]
This has been bugging me too, finally had a look a it. For me (faulty) behavior is consistent when the tree view's scroll is located _below_ the active file.

The culprit seems to be in the [`scrollToEntry` method, where the calculated top-position is wrong]https://github.com/atom/tree-view/blob/master/lib/tree-view.coffee#L659-L660). 

However, looking at the source code from what I can see the [parent directories are expanded](https://github.com/atom/tree-view/blob/master/lib/tree-view.coffee#L302-L303) before changing scroll, before centering on the selected item, so why not simply do a `entry.scrollIntoViewIfNeeded(true)` there (which takes care of scrolling to the expected position) instead of calculating things yourself?
