### ISSUE TITLE
Hide VCS ignored files not working with multiple folders

### ISSUE THREAD

**Issue by Stanzilla** [atom/tree-view#542]
When you add multiple project folders to a window, `Hide VCS ignored files` only applies to the first one. I could be wrong though, as in that the option I really want is `Hide ignored names`.
![2015-07-30_19-20-21](https://cloud.githubusercontent.com/assets/75278/8990035/1e66ee1a-36f0-11e5-944c-90bb0d5fe243.png)

**Comment by CannibalVox** [comment]
I'm having this problem too.  The VCS behavior is really bad when working with multiple root folders, actually.  I've also seen some crashes when changing the "Hide VCS Ignored FIles" value with multiple folder, although I can't repro it.

**Comment by jrial** [comment]
Same here: I work on projects where I have multiple folders open related to the same project, each existing in their own git repo. hiding gitignored files and displaying git status only happens when I load the folders as separate projects, not when I load their parent folder as one project.

Ideally, it would notice every folder to be a repo (presense of .git folder, or equivalent for other VCS's) and apply the ignore on a per-repo basis.

**Comment by 50Wliu** [comment]
@Stanzilla I can't reproduce your issue.
@jrial your issue is atom/atom#2203.

**Comment by Stanzilla** [comment]
Dude that was 3 years ago :D

**Comment by 50Wliu** [comment]
Just cleaning up some old issues ;)
