### ISSUE TITLE
Don't auto-reveal the file while switching between tabs

### ISSUE THREAD

**Issue by monoblaine** [atom/tree-view#563]
**Please**, add an option to disable this behavior. I only use the keyboard during coding, and this behavior makes me insane:
1. Focus on the tree-view using the shortcut for `tree-view:toggle-focus`
2. Press `Enter` to open a file (Suppose `abc.js`).
3. Press `Ctrl+Tab` (or whatever) to switch to another file (`def.js`).
4. Focus on the tree-view again using the keyboard shortcut.
5. The `def.js` is focused now. But I'd like to have `abc.js` remain focused.

**Comment by ypresto** [comment]
Related to https://github.com/atom/tree-view/issues/738#issuecomment-223133421

**Comment by Ben3eeE** [comment]
The feedback here is to not [SelectActiveFile](https://github.com/atom/tree-view/blob/57c3bfb37ce1418418f5505ae1332cdf1c4bfccd/lib/tree-view.coffee#L141) when changing pane items.

This might be good since we have the `Auto Reveal` option for selecting entries when they become the active pane item which also expands folders and scrolls to the current item.

**Comment by lee-dohm** [comment]
Disabling `tree-view:autoReveal` will solve this.
