### ISSUE TITLE
Poor UX with Drag and Drop Files Folders

### ISSUE THREAD

**Issue by eccegordo** [atom/tree-view#566]
I think this is the right place to report this issue. If not please let me know.

As of Atom 1.0.7 Drag and Drop folders and files and were added as a feature.

While the drag drop is a nice feature, there is a subtle jankiness to current implementation. In my day to day experience, I find it far too easy to drag and drop some folder into another folder and not realize I have done so. Haplessly moving stuff around in my project.

I think part of the problem is the lack of visual indication. OS X solves this problem I believe with spring loaded folders and usually a little green plus circle to indicate you are intending to copy something. 

I am surprised at how hair trigger the drag and drop is. Probably needs some careful review of the event handling and behaviors.

At least two things needed:

1.) More obvious visual indication that a move or copy is about to happen.

2.) Some way to cancel mid flight. I believe this is often handled by dragging away and release of mouse button.

Also, how do you disable this feature currently?

Thanks!

**Comment by saschagehlich** [comment]
> 1.) More obvious visual indication that a move or copy is about to happen.

We can indeed change the icon that is displayed while dragging. I already tried to implement copying files - but for this you'd need to get a keydown event (CMD on Mac, I believe CTRL in Windows) while dragging. And the current version of Chrome doesn't emit any keyboard events while dragging

> 2.) Some way to cancel mid flight. I believe this is often handled by dragging away and release of mouse button.

This works on my end. Pressing ESC also works for me.

**Comment by danhigham** [comment]
+1 for disabling drag and drop in the tree, I have moved folders accidentally too many times to count!

**Comment by billybonks** [comment]
currently the drag and drop feature, holds the icon at the top left. changing it to hold the file from the bottom right could be a good improvement.

it's also the same colour as the rest of the folders so gets lost if you aren't paying attention. we could change the colour to make it more obvious.

i don't mind adding a config to disable it or require a key down to initiate the event. as long as its not the only way, i like it as it is now.

**Comment by sergiu-paraschiv** [comment]
+1 for the disable option

**Comment by Zireael07** [comment]
What do you mean it's the same color as the rest of the folders?

**Comment by billybonks** [comment]
![screen shot 2015-10-19 at 7 35 40 pm](https://cloud.githubusercontent.com/assets/1640136/10576805/a90fdbc0-7698-11e5-834f-d9e1a3bc6adf.png)
@Zireael07. i am currently dragging a file in the screenshot. :)

**Comment by stgogm** [comment]
+1111 It's becoming really anoying...

**Comment by theonedemon** [comment]
+1

**Comment by jaunkst** [comment]
A function key or combination should be pressed to unlock file/folder dragging. I love the feature but hate how often i break my projects.

**Comment by cstockton** [comment]
I happen to have screwed up this morning very badly without realizing it and lost a couple weekends of code. Completely my fault- can't blame Atom, poor project layout, lack of a backup, I fail.. but dang.. still sucks lol. What happened is I have a Go project that I was rerunning Ginkgo unit tests on file system changes.. I accidentally dragged the entire sub-package I've been working on down one folder into a transient folder that was deleted and recreated each Ginkgo test run. Derp.

That said, is there no way to disable this feature all together? Just disallowing moving a "project" folder to be moved I am not sure is enough. The worst thing about this feature is it can happen so quickly while working that you have no idea what moved to where. I manage files through a shell exclusively so I can only ever move a folder by accident.

**Comment by mpolichette** [comment]
I'm in favor of being able to disable this feature.  I have been caught in confusion because I had no idea what had happened to a folder after I accidentally dragged it into another which was closed.

Finally, if i do want to move files, I usually want to use `git mv` so my SCM is aware of my intentions.

**Comment by jaunkst** [comment]
I want both. There has to be a way i can drag and drop files, but not completely by accident

**Comment by garfieldbanks** [comment]
For now you can just recompile tree-view:
cd ~/.atom/packages
git clone https://github.com/atom/tree-view
cd tree-view
git checkout c153f67
grep -rl "@draggable = true" . | xargs sed -i "s/@draggable = true/@draggable = false/g"
npm install
sudo npm link
apm rebuild
To update after new releases run these commands again:
npm install
apm rebuild

**Comment by Zireael07** [comment]
What does this recompiling achieve?

**Comment by garfieldbanks** [comment]
Prevents irreversible accidental project destruction.

**Comment by 50Wliu** [comment]
@garfieldbanks Please use `apm install` instead of `npm install`.  The two are subtly different.

**Comment by KenBridgeman** [comment]
First timer here and I've been playing with tree-view.

First, I modified the packages.son to add an 'allowDragAndDrop' configuration setting.
```javascript
    "allowDragAndDrop":{
      "type": "boolean",
      "default": true,
      "description": "Allow drag and drop of folders and files."
    }
```

And I modified both file-view.coffee and directory-view.coffee as such:
```javascript
@draggable = atom.config.get('tree-view.allowDragAndDrop')
```

It works, but only if you exit Atom and restart. Seems to me that's not acceptable.  We would want it to work as soon as you change the setting.

To do so, the following hack works, but it's really a hack because visually it looks like you can drag and drop but nothing happens.

```javascript
    @on 'dragstart', '.entry', (e) =>
        if atom.config.get('tree-view.allowDragAndDrop')
          @onDragStart(e)
    @on 'dragenter', '.entry.directory > .header', (e) =>
        if atom.config.get('tree-view.allowDragAndDrop')
          @onDragEnter(e)
    @on 'dragleave', '.entry.directory > .header', (e) =>
        if atom.config.get('tree-view.allowDragAndDrop')
          @onDragLeave(e)
    @on 'dragover', '.entry', (e) =>
        if atom.config.get('tree-view.allowDragAndDrop')
          @onDragOver(e)
    @on 'drop', '.entry', (e) =>
        if atom.config.get('tree-view.allowDragAndDrop')
         @onDrop(e)
```

Please be kind, as this is a) my first time writing javascript, b) and the first time posting to an OpenSource project.  Thanks for any advice.

**Comment by KenBridgeman** [comment]
Everything from above worked as expected.  I have found no bugs interactively.

I have run the existing spec and it passes...

But, now I have to add to the spec, and I'm struggling.  I could use some help.  I wrote the following spec code that runs without a compiler error

```javascript
  describe "when a directory is single-clicked open", ->
    describe "when allowDragAndDrop configuration item unchecked", ->
      beforeEach ->
          atom.config.set('tree-view.allDragAndDrop', false)

      it "makes all visible folders and files in root1 non-draggable", ->
        root1.click()
        treeView.roots[0].collapse()

        expect(treeView.roots[0]).not.toHaveClass 'expanded'
        root1.trigger clickEvent({altKey: true})
        expect(treeView.roots[0]).toHaveClass 'expanded'

        children = root1.find('.directory')
        expect(children.length).toBeGreaterThan 0
        children.each (index, child) ->
          expect(child).toHaveClass 'expanded'
          expect(child.hasAttribute('draggable')).toBe(true)
          expect(child.getAttribute('draggable')).toBe('false')

      afterEach ->
        atom.config.set('tree-view.allDragAndDrop', true)
```

The following line however fails the expectation.

```javascript
      expect(child.getAttribute('draggable')).toBe('false')
```

If I test it interactively the drag and drop functionality is off, implying that draggable = false.

The only thing I can think is that I am looking at the wrong DOM item, but I haven't a clue.

**Comment by KenBridgeman** [comment]
For those following the solution ...

I had some kind of closure problem that I don't understand with the above code as well as **allDragAndDrop** should have been **allowDragAndDrop**.

This code ensure  **draggable** attribute on directory and file elements are 'false', when **allowDragAndDrop** is false.

```javascript
  describe "when allowDragAndDrop is false", ->
    [dirView, fileView1, fileView2, fileView3, treeView, rootDirPath, dirPath, filePath1, filePath2, filePath3] = []

    beforeEach ->
      atom.config.set('tree-view.allowDragAndDrop', false)
      rootDirPath = fs.absolute(temp.mkdirSync('tree-view'))

      dirPath = path.join(rootDirPath, "test-dir")
      filePath1 = path.join(dirPath, "test-file1.txt")
      filePath2 = path.join(dirPath, "test-file2.txt")
      filePath3 = path.join(dirPath, "test-file3.txt")

      fs.makeTreeSync(dirPath)
      fs.writeFileSync(filePath1, "doesn't matter")
      fs.writeFileSync(filePath2, "doesn't matter")
      fs.writeFileSync(filePath3, "doesn't matter")

      atom.project.setPaths([rootDirPath])

      dirView = $(treeView.roots[0].entries).find('.directory:contains(test-dir)')
      dirView[0].expand()
      fileView1 = treeView.find('.file:contains(test-file1.txt)')
      fileView2 = treeView.find('.file:contains(test-file2.txt)')
      fileView3 = treeView.find('.file:contains(test-file3.txt)')
      treeView.updateRoots()

      it 'makes expanded directory and files draggable', ->
        console.log(dirView[0].getAttribute('draggable'))
        expect(dirView[0].hasAttribute('draggable')).toBe(true)
        expect(dirView[0].getAttribute('draggable')).toBe('false')
        expect(fileView1[0].hasAttribute('draggable')).toBe(true)
        expect(fileView1[0].getAttribute('draggable')).toBe('false')
        expect(fileView2[0].hasAttribute('draggable')).toBe(true)
        expect(fileView2[0].getAttribute('draggable')).toBe('false')
        expect(fileView3[0].hasAttribute('draggable')).toBe(true)
        expect(fileView3[0].getAttribute('draggable')).toBe('false')
        atom.config.set('tree-view.allowDragAndDrop', true)
```

Similar code for when **allowDragAndDrop** is true.

**Comment by KenBridgeman** [comment]
Created pull request #748

**Comment by jellymann** [comment]
👍  Please I have wasted hours due to failing specs for "no reason" until I find out one of my folders was mysteriously "missing". Thank goodness for source control, though 😅

**Comment by marceloLiberton** [comment]
Hello folks, I've coded a simple (aka ugly) solution to this problem (who as killing me).
I've put my "tree-view package" into .atom/packages folder (osx).

Commit: https://github.com/Liberton/tree-view/commit/e61b66ab68dca69009b4ed1875f2d50f08024b38

Any filetype/folder... :)
![simple_solution_dd_atom](https://cloud.githubusercontent.com/assets/4874089/21459919/11e2b02a-c92a-11e6-82ec-f5f989c99363.gif)

**Comment by strindhaug** [comment]
I find it strange that you still flat out refuse to make it possible to disable drag and drop completely (without modifying your own fork of tree-view and changing `@draggable = true` to `@draggable = false` in a few files)...

Why not at least read this value from an environment variable or something; so that we can disable this once and for all without being forced to maintain a fork ourselves?

**Comment by cstockton** [comment]
I agree with @strindhaug - while it's Atom's project and maintainers sometimes have passionate UX views... this specific problem causes frustration at least and data loss at the extreme https://github.com/atom/tree-view/issues/566#issuecomment-168518376.

To see the maintainers all claim config-bloat https://github.com/atom/tree-view/pull/623#issuecomment-151223447 https://github.com/atom/tree-view/pull/623#issuecomment-151224340 for something like this is a bit odd to me as well @strindhaug. Not to mention "better ux" still has not come, no prompts, no delays, you can still move a file in a quick instant without ever seeing where it ended up. This happens the most when I  try to double click really quickly to get a file open and for one reason or another it doesn't register properly. There is not even a basic console log entry like "moved file Y to X", it's completely untraceable and relies entirely on cognitive awareness of a single moment in time.

This sort of cognitive load is not good UX and atom users do not achieve a net reduction in cognitive load by not having to view a single checkbox in a preferences pane- something that remains dormant at all times except when visited specifically at the developers consent when they are looking to modify the behavior of the feature. Unexpected drags happen at the worst possible time- while trying to write software. The argument of "checkbox allergies" makes even less sense when you actually OPEN the tree view and see 46 keybinds taking up a ton of real-estate along with 9 existing checkboxes. If real estate is so important then why do we have hot keys for users with 9 developer panes?

```
cmd-6	tree-view:open-selected-entry-in-pane-6	.platform-darwin .tree-view	Tree View
cmd-7	tree-view:open-selected-entry-in-pane-7	.platform-darwin .tree-view	Tree View
cmd-8	tree-view:open-selected-entry-in-pane-8	.platform-darwin .tree-view	Tree View
cmd-9	tree-view:open-selected-entry-in-pane-9	.platform-darwin .tree-view	Tree View
```

I propose that at the very least a console log entry is made when files are moved by dragging. If it's a folder, just list the folder. Better would be a global var that is checked so a plugin could be made. Best would be a setting because I think this is far more worthy than developers being able to open windows in their 7th 8th and 9th open panes.. while inside the tree view.

**Comment by TomDino** [comment]
Is this going to be fixed or will they keep closing the tickets whenever people line up to complain of the same issue? Really annoying issue with an otherwise spectacular piece of software.

**Comment by cstockton** [comment]
@TomDino I've noticed an unfortunate trend in developer facing UI/UX that seems to aim for the same simplicity you would expect for non-technical end users. It seems a gentle reminder is needed that our field is much more nuanced and configuration is paramount and we are much more resilient to complexity. Lets try to remember the below two links have the same customer.

  - http://electron.atom.io/docs/api/
  - https://atom.io/

**Comment by 50Wliu** [comment]
The reason issues are being closed are because they are duplicates of this issue and serve no purpose other than to redirect our efforts in order to close them.

**Comment by strindhaug** [comment]
@50Wliu If you seriously aren't able to find any more "tickets" related to this here's a few:
#588 #623  #919 #996

**Comment by lee-dohm** [comment]
@strindhaug your comment was deleted as a violation of the [Atom Code of Conduct](https://github.com/atom/atom/blob/master/CODE_OF_CONDUCT.md) as it was insulting or derogatory. You may consider this an official warning.

**Comment by lee-dohm** [comment]
Since drag-and-drop was initially implemented, the two things that were marked as originally needed have either been implemented or shown up as part of the natural upgrade process of successive versions of Electron:

* There is a more obvious visual indication that dragging is occurring (see screenshot)
* Canceling mid-flight can be achieved by pressing <kbd>Esc</kbd> (which is an OS standard way of doing this)

Because of this, I'm going to close this issue.

We aren't going to be implementing a configuration option to disable drag-and-drop. If you're interested in being able to adjust the sensitivity of the drag-and-drop threshold, you may want to subscribe to or comment on [the Chromium bug for it](https://bugs.chromium.org/p/chromium/issues/detail?id=653490).

If there are other more specific issues with drag-and-drop that people would like addressed, please open a new issue.

Thanks everyone for your feedback on this and wanting to help make Atom better.

**Comment by sass94** [comment]
Guys,I have asked several times about how the heck I subscribed to this crap.  I have no idea what this codestuff or Github is and id love to get out of it.
Thanks,  Sorry,  IDK what to do to un subscribe. 

    On Thursday, May 4, 2017 4:39 PM, Lee Dohm <notifications@github.com> wrote:
 

 Closed #566.—

**Comment by 50Wliu** [comment]
@sass94 Here's how to unsubscribe: navigate to https://github.com/atom/tree-view/issues/566 in a browser and make sure you are logged in to your GitHub account.  There should be a right sidebar that has a "Unsubscribe" button - click that and you should be good to go.

Here's the help article: https://help.github.com/articles/unsubscribing-from-conversations/

**Comment by Zireael07** [comment]
> We aren't going to be implementing a configuration option to disable drag-and-drop. 

Why are you so opposed to having a toggle for this?

**Comment by lee-dohm** [comment]
> Why are you so opposed to having a toggle for this?

We're not going to spend time and effort maintaining it in the Atom codebase that the Atom maintainer team is responsible for because:

* It increases the complexity of the code
* It increases the support cost of the application (documenting, explaining how it works or doesn't, etc)
* There are higher priority things for us to work on
* Atom is built to be hackable so that the Atom maintainer team doesn't have to implement every feature that people want

**Comment by Zireael07** [comment]
Regarding point 3, fair point, regarding 4, is there a package for this?

**Comment by lee-dohm** [comment]
I don't see one that offers the ability to turn off drag-and-drop, no.

**Comment by warren-bank** [comment]
fwiw.. [here](https://github.com/warren-bank/atom-tree-view-nodnd) is an easy way to update the package yourself.. to add these config options

**Comment by benyanke** [comment]
Why is the atom team so adverse to providing a toggle to disable drag and drop? Multiple times last week, I broke my application with accidental drags, only to have to manually move files back once I realized what happened. It's supposed to be a modular editor, but that doesn't mean the admins need to be adverse to providing features in core that large portions of the userbase find useful to their workflow. I haven't seen a single positive comment about drag and drop tree view.

```
We're not going to spend time and effort maintaining it in the Atom codebase that the Atom maintainer team is responsible for because:

It increases the complexity of the code'
It increases the support cost of the application (documenting, explaining how it works or doesn't, etc)
```

How difficult is a single boolean toggle to maintain?

**Comment by lee-dohm** [comment]
> How difficult is a single boolean toggle to maintain, especially when it's one requested by the userbase?

Because Atom is open source, you always have the option to fork the tree-view package and support the feature for yourself.

**Comment by warren-bank** [comment]
Personally, I don't understand the friction to adding a boolean `atom.config` option.. that would allow the user to change its value in the package `Settings`.

But, given this reality.. couldn't we at least give the user a hidden way to change this default value using an environment variable?

for example, here's a super simple code change that would resolve this issue:
* from:
&nbsp;&nbsp;`@draggable = true`
to:
&nbsp;&nbsp;`@draggable = (! process.env['atom-tree-view-disable-drag-drop'])`

usage:
* defaults to: `true`
* to disable globally, append to `~/.bashrc`:
&nbsp;&nbsp;`export atom-tree-view-disable-drag-drop=1`
* to disable for a single run:
&nbsp;&nbsp;`(atom-tree-view-disable-drag-drop=1; atom)`

> Because Atom is open source, you always have the option to fork the tree-view package and support the feature for yourself.

to this point, it looks like everybody has..

* [fork](https://github.com/warren-bank/atom-tree-view-nodnd) by me
* [fork](https://github.com/benyanke/tree-view-no-drag) by benyanke
* fork by ...

But, isn't this silly?
Why did such a simple thing turn into a tug-of-war between users and developers.

Power users love options.. the more we can configure the tools we use, the happier we are with them.

**Comment by lee-dohm** [comment]
> couldn't we at least give the user a hidden way to change this default value using an environment variable?

Having an option of any kind, whether in the `atom.config` or environment variable, doesn't resolve any of the issues that I listed before:

* It increases the complexity of the code
* It increases the support cost of the application (documenting, explaining how it works or doesn't, etc)
* There are higher priority things for us to work on
* Atom is built to be hackable so that the Atom maintainer team doesn't have to implement every feature that people want

> But, isn't this silly?
> Why did such a simple thing turn into a tug-of-war between users and developers.

No, I don't think it is silly at all. This is working exactly the way things should in open source. We don't want to maintain this feature that some people want. Those people want the feature badly enough that they decide to maintain it themselves. The only reason there is a tug-of-war here is because people are attempting to coerce the Atom maintainer team into supporting something we don't want to or believe we should have to support.

**Comment by KenBridgeman** [comment]
I forked it too.  Feel free to use it, but I'm not supporting it.  Cheers.

https://github.com/KenBridgeman/tree-view

**Comment by strindhaug** [comment]
@lee-dohm But how does https://github.com/atom/tree-view/pull/1154 add any maintenance cost for you?

- It's literally just replacing two identical lines with the hardcoded value `true` into same variable set to `not` + a reading a system variable which if undefined defaults to `true` as before. How much extra complexity it that really?

- It doesn't need to have any extra documentation. The users who want this fix are developers; who've probably modified the mentioned lines of code themselves a few times. If https://github.com/atom/tree-view/pull/1154 were merged, developers would find those lines and realize that they can just set a variable to disable it.

- It might not be a priority to you, but the fix is minimal, and doesn't require much development at all beyond clicking merge once. (In fact, repeatedly dismissing your users valid complaints, and wontfix'ing their pull request again and again is most likely _more_ work than accepting a pull request causes).

- Yes, it's hackable. But since the variable we want to hack is hardcoded to `true` we have to fork instead of just changing a setting.

On the other hand, for everyone forced to maintain their own fork, it's work _every time_ they want to update (or they'll be stuck with an old version, as I basically am, because I can't be bothered to re-apply the patch all the time). I also love Atom, it's just this one minor annoyance we want to fix properly.

**Comment by lee-dohm** [comment]
> It's literally just replacing two identical lines with the hardcoded value true into same variable set to not + a reading a system variable which if undefined defaults to true as before. How much extra complexity it that really?

Exactly that much extra complexity.

> It doesn't need to have any extra documentation.

Documentation was only one example of support cost. I've had to support multiple features both exposed by configuration and hidden (whether configurable but not shown or by environment variable), they all require effort to support, whether by documentation or some other means. The hidden ones require _more_ support because then we have to explain to the people that don't have the time to go rifling through the code how to activate the feature.

> In fact, repeatedly dismissing your users valid complaints, and wontfix'ing their pull request again and again is most likely more work than accepting a pull request causes

I agree that it is frustrating to have to repeatedly tell people no when they refuse to take no for an answer. Generally though, not listening when someone says "no" is considered bad form.

> for everyone **forced** to maintain their own fork

(Emphasis mine.) We aren't forcing anyone to do anything. We have made a choice. You are free to make your own choice: to maintain your own fork or not. If you really want this feature, then maintaining your own fork is a viable option. If it isn't that important to you, then maybe not maintaining a fork is the right way to go. We respect your right of self-determination, especially in deciding how much your own time is worth and the best use of that time. Please respect ours.

**Comment by benyanke** [comment]
I'm new to atom packages, but if it gets an install base, I'd happy to keep this very simple fork up to date, with a hardcoded disable of drag and drop. In any case, it's working on the current version.

I'll keep an eye on the download counts in the atom package store to see if I decide to go with ongoing maintenance (which could perhaps even be scripted, since it's a search/replace for true/false).

https://github.com/benyanke/tree-view-no-drag
https://atom.io/packages/tree-view-no-drag

**Comment by warren-bank** [comment]
So long as users are aware of the [security risks](https://discuss.atom.io/t/whats-the-security-story-for-package-installation/9578/6) in installing 3rd party packages.. and giving them permission to update automatically. Personally, I'm far too paranoid about security.

**Comment by benyanke** [comment]
@warren-bank 

You could also use something like this, and rebuild yourself.

`grep -rl "@element.draggable = true" $dir  | grep -v ".git" | xargs sed -i "s/@element.draggable = true/@element.draggable = false/g"`

**Comment by warren-bank** [comment]
well.. check my repo that I linked to earlier.. it does something similar.. but on steroids++

**Comment by warren-bank** [comment]
my point is.. I assume that security concerns are the reason that everybody here is maintaining their own individual fork

**Comment by benyanke** [comment]
Fully agree. While it's true that it technically adds complexity, it's a negligible amount...not to mention, all features "add complexity," but if they are features people need, that's the entire point of the software....

**Comment by benyanke** [comment]
Note, to those who followed this thread:

> Given that we're not going to take on significant work on the tree view any time soon, adding this checkbox, while less than ideal, feels like the right thing now.
> I can't re-open this PR because the source repo is gone, but we'd accept a good PR adding this. I'll reopen #588.

[source](https://github.com/atom/tree-view/pull/623#issuecomment-330957065)
