### ISSUE TITLE
Windows: expanding a folder in the tree view locks it and it cannot be deleted

### ISSUE THREAD

**Issue by andreialecu** [atom/tree-view#718]
This is a now almost two year old issue described in: https://github.com/atom/atom/issues/3365

Relevant line:
https://github.com/atom/tree-view/blob/5a9656bc6ec9b75aa00bc89fa19dc52c56449f0c/lib/directory.coffee#L154

Related:
https://github.com/atom/node-pathwatcher/issues/101
https://github.com/nodejs/node/issues/375

`libuv` in node apparently fixed this a while ago by adding a recursive flag which supposedly helps with not locking the folder any more:
https://github.com/joyent/libuv/pull/1473#issuecomment-69878443
Just need to set up the watch at the top level.

Also brackets had a similar issue and they fixed it here:
https://github.com/adobe/brackets/issues/6551

**Comment by lee-dohm** [comment]
Thanks for all the information. Rather than opening an additional issue, I think we'd like to keep tracking it in the original. I've notified the developers of the information you've shared.

**Comment by kumarharsh** [comment]
@lee-dohm apparently it's been discovered [here](https://github.com/atom/atom/issues/3365#issuecomment-235845688) that the responsibility for fixing the locking problem is with tree-view, but apparently no new issue was raised. Perhaps this can be opened?

**Comment by Ajedi32** [comment]
@lee-dohm To be clear, one of the maintainers of the repository which the [original issue](https://github.com/atom/atom/issues/3365) was opened on (@50Wliu) has [suggested](https://github.com/atom/atom/issues/3365#issuecomment-236373865) that a new issue be opened here on this repository. Rather than do that, it seems like it'd be better to just reopen this issue instead.
