### ISSUE TITLE
Tree view keeps opening when I use open-in-project (CTRL+P) or I switch tabs.

### ISSUE THREAD

**Issue by johnmccutchan** [atom/tree-view#738]
I like to keep the tree view hidden (CTRL+) and I like to open files with CTRL+P. But, whenever I press CTRL+P the tree-view gets re-opened.

This also happens when switching tabs. How can I keep the tree-view hidden?

**Comment by lee-dohm** [comment]
You can always disable the tree-view package if you don't want to ever see it. Or is it that you want to see it, but only when you tell it to open?

**Comment by johnmccutchan** [comment]
I'm not going to disable the tree-view because I sometimes want to use it. My expectation is that when I hide something it stays hidden.

**Comment by johncblandii** [comment]
This is so annoying and once worked perfectly. Please revert whatever commit made it open by default.

+1 @johnmccutchan

**Comment by lindseyhanna-wf** [comment]
Yes, please fix. I also like to keep the tree view hidden most of the time but it's a useful feature to have. @johnmccutchan nailed it.

**Comment by johnmccutchan** [comment]
What is the status of this being fixed? The tree-view is just annoying spam at this point.

**Comment by eviljoe** [comment]
This started happening to me when I enabled the auto-reveal option for the tree view (see #796).  Does this still happen to you when you disable that option?

**Comment by johnmccutchan** [comment]
@eviljoe I have auto-reveal turned off and this still happens.

**Comment by ypresto** [comment]
@johnmccutchan FYI: There is auto-reveal-in-sidebar package and it can do same behavior to auto-reveal option. Please make sure it is not installed.

**Comment by vraravam** [comment]
My usecase is slightly different: I want the tree-view to be open all the time, but with the "auto-reveal" feature, the tree-view captures focus. When I open a file or switch the active text editor, all I was to happen is to reveal the file, but the focus should still remain on the text editor.

**Comment by tjgerot** [comment]
@lee-dohm Status check?

**Comment by lee-dohm** [comment]
As far as I can tell, the only people experiencing this issue either:

1. Have `tree-view:autoReveal` enabled
1. Have some other package that offers the same functionality

Since this is the expected behavior in both cases, there isn't anything to be fixed here.

@vraravam Your issue is caused by having both `tree-view:autoReveal` and `tree-view:focusOnReveal` enabled. If you disable `tree-view:focusOnReveal`, things will work the way you want.

**Comment by lee-dohm** [comment]
@johnmccutchan Please open a new issue and fill in the template with as much information as you can, including a list of installed packages.

**Comment by johnmccutchan** [comment]
@lee-dohm How about you stop wasting my time by asking me file a bug after you just closed the bug I filed. You have consistently ignored feedback from many users of Atom on this issue. Community interaction like this are why I'm done with Atom and will use an alternative.

**Comment by lee-dohm** [comment]
I spent a bunch of time yesterday attempting to reproduce the problem as described in the original issue. I was unable to. I want to help fix whatever is going wrong. In order to do that, we're going to need more information and the information most likely to help is the information we ask for in the new issue template. That's why I asked you to fill out a new issue.

Can you meet us half way and give the information that is included in the new issue template?

* Can you reproduce the problem in Safe Mode?
* What are the exact steps you use to reproduce the problem? What did you expect to happen and what actually happened?
* What version of Atom are you experiencing the problem on?
* What OS and version are you running?
* Can you give us any additional information that might help track down what is different about your configuration?

I understand that this is frustrating and I am trying to help.

**Comment by zweiler** [comment]
I'm seeing this same behavior. It's a bit of an edge case, and I'm happy to modify init.coffee or use some other workaround if you can point me in the right direction.

I have ```tree-view:autoReveal``` enabled because I like the functionality, but that auto-reveal switches focus to the tree-view and expands it. This is reasonable behavior, but what I would like to happen is for the auto-reveal to only happen if the tree-view is expanded, and not focus/expand the tree-view if it's hidden. Is there a good way to enable that?

- Yes to safe mode
- Are the steps above sufficient for repro?
- Atom v1.18.0
- macOS Sierra v 10.12.5
- I don't believe I have any other configuration that would be relevant, I've disabled all packages and still see the same behavior

**Comment by UnbendableStraw** [comment]
I have the same issue, really really really really really really really really really really really really really really really really really really really really really really really really really really really really really really  freaking frustrating that no matter what I try it keeps opening when I click on my document.

EVEN DISABLING THE TREE VIEW PACKAGE JUST BRINGS IT BACK AND THEN I CANT EVEN HIDE IT. I have to re-enable it to hide it,just to have ot open back up when switching between documents/tabs

This even happens after clean install. I have no funny business. I also just lost all my opened work so I'm done with atom.

**Comment by alejandrolacasa** [comment]
This is still happening in Atom v1.21.0-beta2, are there any plans to fix it? It is indeed VERY annoying...
