### ISSUE TITLE
Tree view immediately unfocuses (master only)

### ISSUE THREAD

**Issue by mrapogee** [atom/tree-view#740]
I downloaded the master and linked it to work on a feature, and noticed the tree view immediately un-focuses files on-click. You need to quadruple click to get a file to focus so you can run `d` or `m`.

![](http://g.recordit.co/g8GBZTuDVJ.gif)

I'm on OS X 10.11.

**Comment by lee-dohm** [comment]
Reproduced on Atom v1.7.0-dev-41161dd on Mac OS X 10.11.3.

**Comment by kuychaco** [comment]
@mrapogee thanks for opening this issue. The tree-view losing focusing on click is actually the intended behavior. This is so that you can jump in and immediately start editing/navigating the file. 

To your point, being able to focus a file in tree-view is certainly desirable, so I've added the ability to do so by clicking a file in tree-view that is already open as the active pane item (see #742). 

Other ways to focus the tree-view would be view the command `Tree View: Toggle` or the keyboard shortcut `ctrl-0`.
