### ISSUE TITLE
Problem with ampersand in folder name

### ISSUE THREAD

**Issue by maximvd** [atom/tree-view#757]
**This issue was first reported and reproduced here:** https://github.com/atom/atom/issues/11030

### Description

- When a folder has an ampersand in the name and you right click and choose "Show in Explorer" it returns the following warning:

> Opening folder in Explorer failed
> 'Test' is not recognized as an internal or external command,
> operable program or batch file.

_("Test' is everything after the &)_

- If you choose a file within that folder Atom return the following warning:

> Opening file in Explorer failed
> The system can not find the path specified.

### Steps to Reproduce

1. Click a folder with an & in the name
2. Right click on the folder and choose "Show in Explorer".

**Expected behavior:** Atom opens the folder in explorer

**Actual behavior:** Atom opens the parent folder and returns an error

### Versions

**Atom version:** 1.5.3
**OS and version:** Windows 10

**Comment by abejfehr** [comment]
I think the issue is [here](https://github.com/atom/tree-view/blob/ab06a0738db0040630d2d7e2e2d263ed723ebfda/lib/tree-view.coffee#L454). I think the [ampersands in the filepath might have to be escaped with carats](http://stackoverflow.com/questions/1327431/how-do-i-escape-ampersands-in-batch-files).

I'd love to work on this, but I don't have a Windows machine to test on 😞

**Comment by 50Wliu** [comment]
@abejfehr I think you mean [this line](https://github.com/atom/tree-view/blob/ab06a0738db0040630d2d7e2e2d263ed723ebfda/lib/tree-view.coffee#L456) :wink:.

Self-assigning since I'm on Windows, though no guarantees if I'll get to this.
