### ISSUE TITLE
Latest release broke tree view

### ISSUE THREAD

**Issue by EvanHerman** [atom/tree-view#790]
This morning there was an update to the Atom editor. Tree view no longer works.

Atom: v1.6.1
Tree-View: v0.203.2

**Comment by EvanHerman** [comment]
No idea what happened. Re-started atom, re-installed the package - and things are now working once again.

The tree view was not toggling, no matter what I did.

It is now re-solved, although I could not tell you what happened to break and fix things.

**Comment by mnquintana** [comment]
Did you install tree-view manually? If so, you should uninstall it, since it is bundled with Atom core, and having a manually installed version of a bundled package can lead to Weird Stuff.

Also, the Tree View won't open if the active window isn't attached to a project (ie. if you haven't opened a file or folder yet) – see https://github.com/atom/tree-view/issues/68 for more information.

**Comment by EvanHerman** [comment]
I did have it installed as a package. I updated to the latest release, and couldn't trigger the tree view to open again.

> Also, the Tree View won't open if the active window isn't attached to a project (ie. if you haven't opened a file or folder yet) – see #68 for more information.

Certainly sounds like it may have been the issue.

So tree-view is now bundled with core? I think I may have installed it via APM - a few weeks ago.

I wIll have to take a second look.


Thanks for the prompt reply!

**Comment by TheTekton** [comment]
Also, make sure to re-enable the package. I did it through the UI, but I think `apm enable tree-view` would work.
