### ISSUE TITLE
Click events are delayed when double-clicking files

### ISSUE THREAD

**Issue by phoenixenero** [atom/tree-view#844]
When I’m trying to double click a file in the tree-view while the scroll bar is not in the "top" position, the first click event scrolls the tree-view UP while the second click event opens the file *directly below* the cursor.

This also happens while I’m double clicking while moving my cursor very fast.

Here's a video to better explain the issue (.mp4)

https://dl.dropboxusercontent.com/u/105405645/video/atom-tree-view.mp4

[Gfycat mirror](https://gfycat.com/AdeptWelcomeCoqui)

In that video, I am double-clicking as fast as I can.

**Comment by phoenixenero** [comment]
Is this ever gonna get fixed? I run to this every single time when working with a pretty file-heavy project.

**Comment by Ben3eeE** [comment]
@phoenixenero The Atom team is very busy and does not have the time or resources to fix every problem right away. Besides this issue was very hard to reproduce (for me) because your `tree-view` is scrolling on single click which I believe is not supposed to happen. So I had to figure out how to get the `tree-view` to scroll on single click before being able to reproduce the problem. This is because I don't have ninja reflexes required to reproduce it when moving the mouse as you mention in your first post.

That being said I was able to reproduce this in Atom 1.8.0 Windows 7 in safe mode.

Here are my steps to scroll the `tree-view` on single click and reproduce this issue, there are other similar steps but this seemed to work every time while others are more random. These also start from an empty Atom window with a public repository.

1. Open Atom in safe mode, `atom --safe`.
2. Ensure you have the `tree-view` setting Auto Reveal on and also the core setting Pending Pane Items on.
3. Open a project folder, I used the `image-view` repository.
4. Expand some folders and resize the Atom window so you have scroll bars visible in the `tree-view`.
5. Scroll to the bottom of the `tree-view` and open a file in a permanent tab by double clicking it, I opened `coffeelint.json`.
6. Open another file in a pending tab. I opened `image-editor-view-spec.coffee`.
7. Scroll the `tree-view` up so the first file, `coffeelint.json`, is no longer visible but `image-editor-view-spec.coffee` is visible.
8. Double click another file, I double clicked `main.coffee`, tree-view scrolls to `image-view.cson` on first click and opens that in a permanent tab on the second click.

If you only single click in the 8th step the `tree-view` is stuck in some bad state where it is always scrolling on single click.

**Comment by phoenixenero** [comment]
Ran Atom in safe mode. Issue did not appear. I had an idea and disabled the tool bar. Everything's working fine. I disabled the full-width mode of the tool bar and now everything's working correctly. Sorry for wasting your time, I will report this issue to the atom `tool-bar` package.
