### ISSUE TITLE
Repos in parent-nested relationship display as clean when dirty

### ISSUE THREAD

**Issue by bahlo** [atom/tree-view#91]
We have a project where all deployed data is in the folder `public`. 
In this folder, we have initialized a new git repository (to track generated files from CoffeeScript or SASS which we don't want to have in our "main" repository and to push only necessary data to our deployment server).

The (great) git status feature shows the folder and some of it's contents as dirty (also in the status bar), even when both repositories are clean.
## Screenshot

![bildschirmfoto 2014-03-18 um 14 54 13](https://f.cloud.github.com/assets/1725839/2448303/d887ad82-aea4-11e3-971d-cf172bfb5976.png)

**Comment by mafiuss** [comment]
I think I bumped into this issue today:

The scenario is this, I have a git repo in a directory named 'TreeViewBug', inside the root folder I created a new directory named 'nestedRepo' I added it to my .gitignore file, I also initialized the nestedRepo as a git repository of it's own.
```shell
treeViewBug santo$ ll
total 16
drwxr-xr-x  13 santo  staff   442B Nov 11 15:33 .git/
drwxr-xr-x   6 santo  staff   204B Nov 11 15:22 ./
drwxr-xr-x   4 santo  staff   136B Nov 11 15:21 nestedRepo/
-rw-r--r--   1 santo  staff    11B Nov 11 15:20 .gitignore
drwxr-xr-x  55 santo  staff   1.8K Nov 11 15:20 ../
-rw-r--r--   1 santo  staff    15B Nov 11 15:19 file.txt
replicant:treeViewBug santo$ ll nestedRepo/
total 8
drwxr-xr-x   6 santo  staff   204B Nov 11 15:22 ../
drwxr-xr-x  13 santo  staff   442B Nov 11 15:22 .git/
drwxr-xr-x   4 santo  staff   136B Nov 11 15:21 ./
-rw-r--r--   1 santo  staff    23B Nov 11 15:21 nestedFile.txt
```
As expected the tree view in atom doesn't display my ignored directories, that being nestedRepo, Then I added (cmd+shift+o) the nestedRepo directory to my project folders,

Expected behavior: the nestedRepo appears in the treeview with all the files

Actual behavior: The nested repo directory appears but shows no files under it.

screenshot:

![screen shot 2015-11-11 at 3 34 30 pm](https://cloud.githubusercontent.com/assets/120338/11103829/8a5974bc-888a-11e5-9c23-52dc55a63931.png)

**Comment by kseniamurex** [comment]
_copied from #932_
Seems like something similar to this issue happened to me. Let's say we have some nested repos like this: 
![](https://cloud.githubusercontent.com/assets/21336215/18124712/1b9cae98-6f7c-11e6-82fc-24359ad79be9.png)
(test1 and test5 are dirty here)
Now I clean my project, add the nested repo first and then the parent repo. So I can check my subrepos and it works fine and sometimes the changes are even shown correctly inside of the parent repo! But the parent repo changes aren't shown at all:
![](https://cloud.githubusercontent.com/assets/21336215/18124724/2e9835ee-6f7c-11e6-96c3-a9ff684a8df5.png)
When I add the parent repo, changes aren't dispalyed. If I now open a changed file, the tree shows that it was changed, but only this opened file, so I have to open them all. Now if I switch to any other window, the tree of the parent repo redraws, and the changes aren't shown again.\
So:

**Steps to Reproduce**
1. Create nested git repos.
2. Add the subrepo to the project.
3. Add the parent repo to the project.

**Expected behavior:** Both parent and child repo changes are dispalyed in the tree view.
![](https://cloud.githubusercontent.com/assets/21336215/18159613/30e4cf68-7032-11e6-9620-577a4c15e0d4.png)

**Actual behavior:** Child repo changes are displayed, parent's are **not**. If you **open a changed file** its changes become displayed (that's how I got the previous screenshot). If you **switch** to another window, the changes aren't displayed again.
![](https://cloud.githubusercontent.com/assets/21336215/18159622/40314c30-7032-11e6-9547-dc74e512791e.png)

**Versions:**
`Atom : 1.9.9 - 1.10.0`
`Electron: 0.37.8`
`Chrome : 49.0.2623.75`
`Node : 5.10.0`

`Linux version 3.13.0-95-generic (buildd@lgw01-58) (gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04.3) ) #142-Ubuntu SMP Fri Aug 12 17:00:09 UTC 2016`
