### ISSUE TITLE
Unable to navigate the tree with page-up/page-down

### ISSUE THREAD

**Issue by padcom** [atom/tree-view#910]
I'd like to be able to navigate the tree view faster using page up/down keys. What works is using the ctrl-home/ctrl-end to go to the beginning/end of the tree but that isn't helping in big directory structures.

**Comment by Aarbel** [comment]
Up

**Comment by 50Wliu** [comment]
Cannot confirm: the `core:page-up`/`core:page-down` commands are working as expected for me on the Tree View.

**Comment by padcom** [comment]
They scroll the view not move the selected element. If that is the intended behavior this is just wrong.

**Comment by Ben3eeE** [comment]
@padcom We are tracking the issue you describe in https://github.com/atom/tree-view/issues/1021

**Comment by padcom** [comment]
Not to be greedy but how's 1021 befoe 910 I can't explain. Because that took so long I already moved away from Atom to VS Code. Sorry...

**Comment by 50Wliu** [comment]
@padcom your issue was not clearly stated - "unable to navigate" implies that page-up/page-down are flat out not moving the Tree View.  #1021 has more helpful information and a better statement of the problem.  We do not close issues as duplicates based on which one came first, but rather which one is more useful to the Atom team when fixing issues.

**Comment by padcom** [comment]
Whatever helps you make the editor better
