### ISSUE TITLE
Add drag and drop threshold setting (or use system default)

### ISSUE THREAD

**Issue by strindhaug** [atom/tree-view#919]
The drag and drop theshold is ridiculous, it appears to be essentially 0px (or 1-2px; it's hard to tell on my high PPI monitor), meaning I cannot click in the tree view without risking accidentally dragging and dropping files or folders. (There is no undo for this either with makes this even more problematic). 

On my system (Ubuntu) in most native apps such as the filemanager the drag theshold is 50px it's stored in dconf under `org.gnome.settings-daemon.peripherals.mouse.drag-threshold` as an integer, presumably this setting is available to all apps. But (assumning this setting *is* available to applications) Atom doesn't use this.

There must be a way to change this threshold to something bigger (preferably without any upper limit, so that we can effectively disable it since having a setting to disable drag and drop was wontfixed: https://github.com/atom/tree-view/pull/623 ).

**Comment by lee-dohm** [comment]
In order to change this, we would have to either fiddle with some low-level Chromium bits or create a complete architecture for how to do drag-and-drop in Atom. Both are a bit beyond what we have the resources available to do at this point. We may revisit this in the future when we have more resources available. If we do, we'll reopen this Issue.

**Comment by strindhaug** [comment]
@lee-dohm so, you're saying this really is a Chromium issue? Actually it seems it may be, just noticed that the tabs in Chrome also starts dragging without a threshold. Maybe I should report this upstream to the chromium project...

**Comment by pwnall** [comment]
Are you guys building your own Chromium? If so, you could patch the values in `third_party/WebKit/Source/core/input/MouseEventManager.cpp`.

FWIW, 50px strike me as excessive. The default values for the OS preferences I've looked at are 3px-8px. Also, AFAIK these are CSS pixels, not actual pixels on a HiDPI screen.

Last, Chromium has [a bug for this issue](http://crbug.com/653490). Unfortunately, based on the current bug popularity vs implementation complexity, I don't expect we'll be able to address it any time soon.

**Comment by lee-dohm** [comment]
:wave: @pwnall The Atom team isn't building our own Chromium, no. We get it as part of [Electron](https://github.com/electron/electron) and use it as-is (though theoretically Electron could do as you suggest if it would make sense for _all_ Electron applications. The Electron team tries to avoid adding more divergences from base Chromium, especially in tricky parts of the code, because then that creates maintenance overhead as we go down the line.

Thanks very much for the advice and the update! I'll pass it along to the Electron team :grinning:
