### ISSUE TITLE
Make use of git for file handling

### ISSUE THREAD

**Issue by exploide** [atom/tree-view#928]
Regarding certain visual indications, tree-view is git aware (ignored files, modified files, etc).

It would be nice if actions like moving or deleting files and folders would trigger `git mv` or `git rm` if the relevant file is under version control.

**Comment by thomasjo** [comment]
I'm massively 👎 on this. We should *not* be using any sort of Git mechanics when it comes to mutating the file system. And no, we do not need more checkboxes (in case anyone was considering proposing making this feature opt-in).

I might consider giving a 👍 to a separate set of commands that explicitly declare that they operate using VCS mechanics; e.g. `tree-view:vcs-move`, `tree-view:vcs-rename`, etc.

**Comment by lee-dohm** [comment]
This kind of functionality is unnecessary because Git figures it all out when you commit, even moves. Because of this, the added complexity of determining whether we should use the Git operations or regular file operations for any particular file and operation combination would be a lot of added work and potential for failure with no upside.

Thanks very much for the feedback!
