### ISSUE TITLE
tree-view panel attribute is unset when opening additional windows

### ISSUE THREAD

**Issue by tbarsballe** [atom/tree-view#953]
Steps to Reproduce:
- Open Atom.
- If an initial window is not opened by default, open a new window.
- Open a(nother) new window. For this window, `_mainJs.treeView.panel` will not be set.

I assume the problem is happening somewhere around here: https://github.com/atom/tree-view/blob/master/lib/tree-view.coffee#L171 , but I am not sufficiently familiar with coffeescript (or how atom works) to be sure.

I discovered this issue while usin the atom-autohide-tree plugin; as a consequence that plugin does not work on additional windows (there appears to be a related bug report here: https://github.com/olmokramer/atom-autohide-tree-view/issues/76 , and the actual failure seems to be occuring [here](https://github.com/olmokramer/atom-autohide-tree-view/blob/master/lib/autohide-tree-view.js#L41) )

**Comment by AndreaGriffiths11** [comment]
Thanks for taking the time to contribute!

When you open a new window using "File > New Window" the new window does not have a project associated with it. Because the new window does not have a project associated  with it the tree view does not show. This is the expected behavior for Atom. Thanks for the information and I hope this helps.
