### ISSUE TITLE
shortcut to collapse all directories recursively

### ISSUE THREAD

**Issue by xh3b4sd** [atom/tree-view#960]
Imagine you have five directories listed in tree-view. Over time there can be a mess when lots of files are opened and revealed. Then you lose the overview of what is there and where. There is a shortcut to collapse one directory recursively but I would like to have also one to collapse all of the directories recursively.

**Comment by 50Wliu** [comment]
This can be done simply by targeting the root directory as the one to recursively collapse.

**Comment by xh3b4sd** [comment]
This does not mean anything to me. Can you elaborate on that?

**Comment by 50Wliu** [comment]
Oh, I think I might have misunderstood your initial question.  Can you please add a screenshot of the tree-view with the five directories just to make sure we're on the same page?

**Comment by xh3b4sd** [comment]
I have several projects listed in tree-view. When they are closed everything is clean. All good.

<img width="1440" alt="screen shot 2016-10-17 at 19 46 32" src="https://cloud.githubusercontent.com/assets/552769/19448499/60274d02-94a2-11e6-91c7-e2ae56ef8d05.png">

Over time there is a mess and you don't know anymore where you are and what is there.

<img width="1440" alt="screen shot 2016-10-17 at 19 45 06" src="https://cloud.githubusercontent.com/assets/552769/19448501/66a20a0a-94a2-11e6-8eeb-9d568017813b.png">

So you can currently collapse one single project folder but not all at once. I am wondering if it would make sense to have a shortcut to cleanup tree-view to have the initial clean state like shown in the first picture again. At this point I need to admit that I am quite new to Atom. I love it. I am still in the phase of figuring out how to work with projects and what packages help me organize projects and get to code.

**Comment by nemesisdesign** [comment]
I have the same issue. [OpenWISP 2](https://github.com/openwisp/ansible-openwisp2) consists of many modules that are assembled into a working application, each module has its own repository, just like atom has its features divided in different packages.
To speed up this kind of workflow I have 10-15 different projects opened at the same time, when I open Atom I'm overwhelmed because every repo is expanded so it takes a lot of time to find what I'm looking for.
I would not only add a collapse all / expand all feature, I would also add a setting that allows the user to specify that folders can be collapsed by default when the editor is opened.

**Comment by 50Wliu** [comment]
Fixed by #960.

**Comment by Greenek** [comment]
You can use [tree-view-auto-collapse](http://atom.io/packages/tree-view-auto-collapse) to keep your tree view clean.
