### ISSUE TITLE
Remove jquery and convert to es2015+/babel

### ISSUE THREAD

**Issue by forivall** [atom/tree-view#980]
I'm wondering if this would be open to a pull request, or if it's just not reasonable to permit right now.

**Comment by lee-dohm** [comment]
This would be a major rewrite, though one we have been thinking on how to accomplish ourselves also. There are a few things to take into consideration:

1. Currently tree-view's UI is built with a combination of space-pen and HTML custom elements. Ideally, this should be replaced with something more maintainable as part of this effort. Right now, our best option to recommend for that is [etch](https://github.com/atom/etch). Unfortunately, we still haven't settled on that library 100% either ... so it could be that we would want it rewritten in something else before ultimately merging back in.
1. Because this would be a large effort, it would probably be best to fork tree-view to create a tree-view-plus community package that could be iterated on with an eye toward eventually merging all of that work back into tree-view to create tree-view v2.0. Unfortunately, this isn't a strategy we have tried before so there may be some hidden pitfalls there as well.
1. It probably goes without saying, but it would be imperative that feature parity is maintained. Feature parity with the tree-view package would be a _bare minimum_ expectation. (Just putting that out there :grinning:)

Does that help?

**Comment by sass94** [comment]
blockquote, div.yahoo_quoted { margin-left: 0 !important; border-left:1px #715FFA solid !important; padding-left:1ex !important; background-color:white !important; }  Just forget about it no big deal just delete it. 


Sent from Yahoo Mail for iPhone


On Thursday, November 10, 2016, 3:59 PM, Lee Dohm <notifications@github.com> wrote:


This would be a major rewrite, though one we have been thinking on how to accomplish ourselves also. There are a few things to take into consideration:
   
   - Currently tree-view's UI is built with a combination of space-pen and HTML custom elements. Ideally, this should be replaced with something more maintainable as part of this effort. Right now, our best option to recommend for that is etch. Unfortunately, we still haven't settled on that library 100% either ... so it could be that we would want it rewritten in something else before ultimately merging back in.
   - Because this would be a large effort, it would probably be best to fork tree-view to create a tree-view-plus community package that could be iterated on with an eye toward eventually merging all of that work back into tree-view to create tree-view v2.0. Unfortunately, this isn't a strategy we have tried before so there may be some hidden pitfalls there as well.
   - It probably goes without saying, but it would be imperative that feature parity is maintained. Feature parity with the tree-view package would be a bare minimum expectation. (Just putting that out there 😀 )

Does that help?

**Comment by lee-dohm** [comment]
We're planning on performing this migration when we get the chance. Unfortunately, it will require a major rewrite so we're having to schedule it rather intentionally. Since this is something we're doing to all packages as we can and as it makes the most sense, this isn't something that we're going to track. I'm going to close this, but if anyone has any questions about this, please let me know :+1:

Thank you for contributing!
