### ISSUE TITLE
Difficult to collapse directory

### ISSUE THREAD

**Issue by seajean** [atom/tree-view#995]
Sometimes I wanna find something in the node_modules directory, then I unfold the node_modules directory, but when this was done, it was very difficult to fold this directory again, I wanna scroll all the way up so I can see the collapse button

**Comment by Ben3eeE** [comment]
Thanks for reaching out!

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* [The Atom Flight Manual](http://flight-manual.atom.io)
* [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.

----

You can use the left and right arrow keys on the keyboard to easily fold and unfold directories.
