### ISSUE TITLE
why tree-view displayed on the right

### ISSUE THREAD

**Issue by wendaosanshou** [atom/tree-view#998]
at frist, the tree-view displayed on the left,  i press `cmd-\` hide the tree-view, but when i press again, the tree-view displayed on the right.
i hope the tree-view displayed on the left, how to restore the location ?

![picture](https://sfault-image.b0.upaiyun.com/172/650/1726500177-5844c79c641d2_articlex)

**Comment by Ben3eeE** [comment]
Thanks for reaching out!

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* [The Atom Flight Manual](http://flight-manual.atom.io)
* [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.

----

In the `tree-view` package settings there is a setting to display on the left or on the right.
